version: 2

models:
  - name: fct_sales
    description: "Fact table containing all sales transactions with customer and product details"
    columns:
      - name: ticket_number
        description: "Unique transaction identifier"
        tests:
          - not_null
      - name: customer_key
        description: "Foreign key to dim_customers"
        tests:
          - not_null
      - name: item_key
        description: "Foreign key to dim_products"
        tests:
          - not_null
      - name: revenue
        description: "Total revenue (extended_sales_price)"
        tests:
          - not_null
        
  - name: dim_customers
    description: "Customer dimension with lifetime purchase metrics and segmentation"
    columns:
      - name: customer_key
        description: "Primary key for customers"
        tests:
          - unique
          - not_null
      - name: customer_name
        description: "Full name (first + last)"
      - name: total_revenue
        description: "Lifetime customer revenue"
        tests:
          - not_null
      - name: customer_segment
        description: "Customer value segment (VIP, High Value, etc.)"
        
  - name: dim_products
    description: "Product dimension with sales performance metrics"
    columns:
      - name: item_key
        description: "Primary key for products"
        tests:
          - unique
          - not_null
      - name: item_description
        description: "Product description"
      - name: total_revenue
        description: "Total revenue generated by this product"
        tests:
          - not_null
      - name: product_performance
        description: "Performance category (Best Seller, Popular, etc.)"