version: 2

models:
  - name: fct_sales
    description: "Sales fact table with all transactions"
    columns:
      - name: ticket_number
        tests:
          - not_null
      - name: customer_key
        tests:
          - not_null
        
  - name: dim_customers
    description: "Customer dimension with lifetime metrics"
    columns:
      - name: customer_key
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: total_revenue
        tests:
          - not_null